論文投稿サイト課題
yasu-swift/journal_site_app pull request #1
Opened 2021-09-20 05:55 UTC by yasu-swift

課題1終了しました

2021-09-20 06:30 UTC, narusesuzuki reviewed
お疲れさまです！課題1バッチリです！🙆‍♂️
課題2もfeatureブランチで進めて、再度slackで教えて下さい！

2021-09-20 21:12 UTC, kazu-taka commented
@yasu-swift 
問題ないので課題3に入ってOKです👍

2021-09-21 02:32 UTC, kazu-taka requested changes
@yasu-swift 
コメントしたので確認お願いします:bow:

2021-09-21 02:32 UTC, kazu-taka commented on resources/views/articles/edit.blade.php
> +            <textarea name="body" id="" cols="30" rows="10">{{ $article->body }}</textarea>
@yasu-swift 
オークションのようにoldメソッドも併用しないと、入力後にバリデーションでNGとなった場合、入力内容が保持されず登録済みの内容に置き換わってしまうので、修正お願いします:bow:

2021-09-21 02:32 UTC, kazu-taka commented on resources/views/articles/show.blade.php
> +        <!-- 惑星のidを元に編集ページへ遷移する -->
@yasu-swift 
コメントが間違っているので(惑星は別課題)修正お願いします:bow:

2021-09-21 04:25 UTC, kazu-taka commented
@yasu-swift 
マージしてOKです！！
![LGTM](https://image.lgtmoon.dev/141041)

2021-09-21 04:27 UTC, merged